# -*- coding: utf-8 -*-
"""Codigo .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fMBUcFDQtYNiRgKV6Y8J7_XjBtUxuGjn
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

VREF = 3.3

# Color asignado a cada ensayo
COLORES = {
    1: "tab:blue",
    2: "tab:orange",
    3: "tab:green",
    4: "tab:red",
    5: "tab:purple"
}

TESTS = {
    1: {"vdmm": 0.599, "soft_mean": 0.597400, "soft_std": 14.451},
    2: {"vdmm": 1.199, "soft_mean": 1.197824, "soft_std": 15.377},
    3: {"vdmm": 1.798, "soft_mean": 1.801162, "soft_std": 15.878},
    4: {"vdmm": 2.399, "soft_mean": 2.404208, "soft_std": 15.542},
    5: {"vdmm": 2.999, "soft_mean": 3.006148, "soft_std": 15.332},
}


def procesar_test(test_id, vdmm, soft_mean=None, soft_std=None):

    samples_file = f"samples_test_{test_id}.csv"
    hist_file = f"histogram_test_{test_id}.csv"

    color = COLORES[test_id]

    # 1. CARGA DE LOS DATOS

    df = pd.read_csv(samples_file)

    df["Raw_u16"] = df["Raw_u16"].astype(int)

    # Conversión de la lectura de 16 bits a voltaje
    df["Voltage_V"] = df["Raw_u16"] * VREF / 65535.0

    # Recuperación del código nominal de 12 bits
    df["Code12"] = (df["Raw_u16"] // 16).astype(int)

    # 2. CÁLCULO DE PARÁMETROS ESTADÍSTICOS

    v_mean = df["Voltage_V"].mean()
    v_std = df["Voltage_V"].std(ddof=1)

    v_min = df["Voltage_V"].min()
    v_max = df["Voltage_V"].max()
    v_range = v_max - v_min

    error_v = v_mean - vdmm
    error_pct = 100 * error_v / vdmm if vdmm != 0 else np.nan

    print(f"\n===== TEST {test_id} =====")
    print(f"VDMM              : {vdmm:.4f} V")
    print(f"Media ADC         : {v_mean:.4f} V")
    print(f"Desviación estándar: {v_std*1000:.3f} mV")
    print(f"Mínimo            : {v_min:.4f} V")
    print(f"Máximo            : {v_max:.4f} V")
    print(f"Rango             : {v_range*1000:.3f} mV")
    print(f"Error             : {error_pct:+.3f} %")

    # 3. COMPARACIÓN CON SAMPLING_2.PY

    if soft_mean is not None:
        diferencia_media = (v_mean - soft_mean) * 1000

        print(f"Media sampling_2.py: {soft_mean:.4f} V")
        print(f"Diferencia media   : {diferencia_media:+.4f} mV")

    if soft_std is not None:
        diferencia_std = (v_std * 1000) - soft_std

        print(f"s sampling_2.py   : {soft_std:.3f} mV")
        print(f"Diferencia s       : {diferencia_std:+.4f} mV")

    # 4. GRÁFICA DE VOLTAJE VS NÚMERO DE MUESTRA

    plt.figure(figsize=(8, 4))

    plt.plot(
        df["Sample"],
        df["Voltage_V"],
        linewidth=0.7,
        color=color
    )

    plt.xlabel("Número de muestra")
    plt.ylabel("Voltaje (V)")
    plt.title(f"Test {test_id}: lecturas del ADC")
    plt.grid(True)
    plt.tight_layout()

    plt.savefig(
        f"test{test_id}_lecturas_vs_muestra.png",
        dpi=150
    )

    plt.show()

    # 5. HISTOGRAMA DE VOLTAJES

    plt.figure(figsize=(6, 4))

    plt.hist(
        df["Voltage_V"],
        bins=30,
        edgecolor="black",
        color=color
    )

    plt.xlabel("Voltaje (V)")
    plt.ylabel("Frecuencia")
    plt.title(f"Test {test_id}: histograma de mediciones")

    plt.tight_layout()

    plt.savefig(
        f"test{test_id}_histograma_voltaje.png",
        dpi=150
    )

    plt.show()

    # 6. HISTOGRAMA DE CÓDIGOS DE 12 BITS (CORREGIDO)

    hist_df = pd.read_csv(hist_file)

    plt.figure(figsize=(6, 4))

    plt.bar(
        hist_df["Code12"],
        hist_df["Count"],
        width=1.0,
        color=color,
        edgecolor="none"  # Al eliminar los bordes de cada barra, el color del test se muestra limpio
    )

    plt.xlabel("Código ADC de 12 bits")
    plt.ylabel("Frecuencia")
    plt.title(f"Test {test_id}: histograma de códigos ADC")

    plt.tight_layout()

    plt.savefig(
        f"test{test_id}_histograma_codigo12.png",
        dpi=150
    )

    plt.show()

    # 7. RESULTADOS

    return {
        "Test": test_id,
        "VDMM_V": vdmm,
        "V_ADC_V": v_mean,
        "s_mV": v_std * 1000,
        "Error_mV": error_v * 1000,
        "Error_pct": error_pct
    }


# PROCESAR LOS CINCO TEST

if __name__ == "__main__":

    resultados = []

    for test_id, cfg in TESTS.items():

        resultado = procesar_test(
            test_id,
            cfg["vdmm"],
            cfg["soft_mean"],
            cfg["soft_std"]
        )

        resultados.append(resultado)

    # TABLA

    tabla = pd.DataFrame(resultados)

    print("\n===== TABLA RESUMEN =====")
    print(tabla.to_string(index=False))

    tabla.to_csv(
        "tabla_resumen_parte2.csv",
        index=False
    )

    print("\nArchivo generado:")
    print("tabla_resumen_parte2.csv")